sudo: false
language: node_js
node_js:
  - 'stable'
  - '6'
script:
  - npm run build
  - npm test
before_deploy:
  - ls -lh s/*.json
  - npm i semver
  - npm version --no-git-tag-version --force $(./node_modules/.bin/semver -i minor $(npm info vbb-station-shapes version))
deploy:
  provider: npm
  on:
    branch: master
    node: stable
  email: 'mail@jannisr.de'
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
